-- INSERT Categories (75 rows)
INSERT INTO Categories VALUES (1, 'Abstract Strategy');
INSERT INTO Categories VALUES (2, 'Action / Dexterity');
INSERT INTO Categories VALUES (3, 'Adventure');
INSERT INTO Categories VALUES (4, 'Age of Reason');
INSERT INTO Categories VALUES (5, 'American Civil War');
INSERT INTO Categories VALUES (6, 'American Indian Wars');
INSERT INTO Categories VALUES (7, 'American Revolutionary War');
INSERT INTO Categories VALUES (8, 'American West');
INSERT INTO Categories VALUES (9, 'Ancient');
INSERT INTO Categories VALUES (10, 'Animals');
INSERT INTO Categories VALUES (11, 'Arabian');
INSERT INTO Categories VALUES (12, 'Aviation / Flight');
INSERT INTO Categories VALUES (13, 'Bluffing');
INSERT INTO Categories VALUES (14, 'Book');
INSERT INTO Categories VALUES (15, 'Card Game');
INSERT INTO Categories VALUES (16, 'Children''s Game');
INSERT INTO Categories VALUES (17, 'City Building');
INSERT INTO Categories VALUES (18, 'Civil War');
INSERT INTO Categories VALUES (19, 'Civilization');
INSERT INTO Categories VALUES (20, 'Collectible Components');
INSERT INTO Categories VALUES (21, 'Comic Book / Strip');
INSERT INTO Categories VALUES (22, 'Deduction');
INSERT INTO Categories VALUES (23, 'Dice');
INSERT INTO Categories VALUES (24, 'Economic');
INSERT INTO Categories VALUES (25, 'Educational');
INSERT INTO Categories VALUES (26, 'Electronic');
INSERT INTO Categories VALUES (27, 'Environmental');
INSERT INTO Categories VALUES (28, 'Expansion for Base-game');
INSERT INTO Categories VALUES (29, 'Exploration');
INSERT INTO Categories VALUES (30, 'Fan Expansion');
INSERT INTO Categories VALUES (31, 'Fantasy');
INSERT INTO Categories VALUES (32, 'Farming');
INSERT INTO Categories VALUES (33, 'Fighting');
INSERT INTO Categories VALUES (34, 'Game System');
INSERT INTO Categories VALUES (35, 'Horror');
INSERT INTO Categories VALUES (36, 'Humor');
INSERT INTO Categories VALUES (37, 'Industry / Manufacturing');
INSERT INTO Categories VALUES (38, 'Korean War');
INSERT INTO Categories VALUES (39, 'Mafia');
INSERT INTO Categories VALUES (40, 'Math');
INSERT INTO Categories VALUES (41, 'Mature / Adult');
INSERT INTO Categories VALUES (42, 'Maze');
INSERT INTO Categories VALUES (43, 'Medical');
INSERT INTO Categories VALUES (44, 'Medieval');
INSERT INTO Categories VALUES (45, 'Memory');
INSERT INTO Categories VALUES (46, 'Miniatures');
INSERT INTO Categories VALUES (47, 'Modern Warfare');
INSERT INTO Categories VALUES (48, 'Movies / TV / Radio theme');
INSERT INTO Categories VALUES (49, 'Murder/Mystery');
INSERT INTO Categories VALUES (50, 'Music');
INSERT INTO Categories VALUES (51, 'Mythology');
INSERT INTO Categories VALUES (52, 'Napoleonic');
INSERT INTO Categories VALUES (53, 'Nautical');
INSERT INTO Categories VALUES (54, 'Negotiation');
INSERT INTO Categories VALUES (55, 'Novel-based');
INSERT INTO Categories VALUES (56, 'Number');
INSERT INTO Categories VALUES (57, 'Party Game');
INSERT INTO Categories VALUES (58, 'Pike and Shot');
INSERT INTO Categories VALUES (59, 'Pirates');
INSERT INTO Categories VALUES (60, 'Political');
INSERT INTO Categories VALUES (61, 'Post-Napoleonic');
INSERT INTO Categories VALUES (62, 'Prehistoric');
INSERT INTO Categories VALUES (63, 'Print & Play');
INSERT INTO Categories VALUES (64, 'Puzzle');
INSERT INTO Categories VALUES (65, 'Racing');
INSERT INTO Categories VALUES (66, 'Real-time');
INSERT INTO Categories VALUES (67, 'Religious');
INSERT INTO Categories VALUES (68, 'Renaissance');
INSERT INTO Categories VALUES (69, 'Science Fiction');
INSERT INTO Categories VALUES (70, 'Space Exploration');
INSERT INTO Categories VALUES (71, 'Spies/Secret Agents');
INSERT INTO Categories VALUES (72, 'Sports');
INSERT INTO Categories VALUES (73, 'Territory Building');
INSERT INTO Categories VALUES (74, 'Trains');
INSERT INTO Categories VALUES (75, 'Transportation');