use board_games;

-- INSERT Creators (75 rows)
INSERT INTO Creators VALUES (1, '"Nero" Ondrej Sova', 'Hub Games');
INSERT INTO Creators VALUES (2, '(Uncredited)', '(Public Domain)');
INSERT INTO Creators VALUES (3, '13Rentgen', '13Rentgen');
INSERT INTO Creators VALUES (4, '326', 'Arclight');
INSERT INTO Creators VALUES (5, '5th Door Designs', 'Playroom Entertainment');
INSERT INTO Creators VALUES (6, 'A. B. J. Lawson', 'Buffalo Games');
INSERT INTO Creators VALUES (7, 'A. Butner', 'Late for the Sky Production Company');
INSERT INTO Creators VALUES (8, 'A. Davis', '3W (World Wide Wargames)');
INSERT INTO Creators VALUES (9, 'A. E. Goodwin', 'Games Research/Design (GR/D)');
INSERT INTO Creators VALUES (10, 'A. Eddie Goldfarb', 'Early Learning Centre');
INSERT INTO Creators VALUES (11, 'A. F. Speer', 'Family Fun & Learning Company');
INSERT INTO Creators VALUES (12, 'A. J. Patterson', 'Damm / Egmont');
INSERT INTO Creators VALUES (13, 'A. J. Porfirio', 'Van Ryder Games');
INSERT INTO Creators VALUES (14, 'A. P. Nienstaedt', '(Unknown)');
INSERT INTO Creators VALUES (15, 'A. Robert Moog', 'Cappelen');
INSERT INTO Creators VALUES (16, 'A. Trevor Pepperell', 'Maruca Industries');
INSERT INTO Creators VALUES (17, 'A. Víctor Rojo Arias', 'Gen-X Games');
INSERT INTO Creators VALUES (18, 'A. W. Compton', '(Self-Published)');
INSERT INTO Creators VALUES (19, 'A. Weiner', 'MB Giochi');
INSERT INTO Creators VALUES (20, 'A.B. Chr. Olsen', 'Ravensburger');
INSERT INTO Creators VALUES (21, 'AC Atienza', 'Buffalo Games');
INSERT INTO Creators VALUES (22, 'AJ Lambeth', 'Kolossal Games');
INSERT INTO Creators VALUES (23, 'AL García', 'Zacatrus');
INSERT INTO Creators VALUES (24, 'Aamir Syed', '(Self-Published)');
INSERT INTO Creators VALUES (25, 'Aaron Andrew Wilson', 'Deep Water Games');
INSERT INTO Creators VALUES (26, 'Aaron Belmer', 'Grey Fox Games');
INSERT INTO Creators VALUES (27, 'Aaron Brosman', 'Arcane Wonders');
INSERT INTO Creators VALUES (28, 'Aaron Burghard', 'neat games');
INSERT INTO Creators VALUES (29, 'Aaron Dack', 'Two Robots, Inc');
INSERT INTO Creators VALUES (30, 'Aaron Darland', 'Wyrd Miniatures');
INSERT INTO Creators VALUES (31, 'Aaron Dill', 'Gale Force Nine, LLC');
INSERT INTO Creators VALUES (32, 'Aaron Fechter', 'Bandai');
INSERT INTO Creators VALUES (33, 'Aaron Forsythe', 'Avalon Hill Games, Inc.');
INSERT INTO Creators VALUES (34, 'Aaron Haag', 'Argentum Verlag');
INSERT INTO Creators VALUES (35, 'Aaron Hanna', 'Hologrin Studios');
INSERT INTO Creators VALUES (36, 'Aaron Holland', 'WizKids');
INSERT INTO Creators VALUES (37, 'Aaron Kluck', 'Portal Dragon');
INSERT INTO Creators VALUES (38, 'Aaron Lauster', 'JKLM Games');
INSERT INTO Creators VALUES (39, 'Aaron Mesburne', 'Brotherwise Games');
INSERT INTO Creators VALUES (40, 'Aaron Pavao', 'Atlas Games');
INSERT INTO Creators VALUES (41, 'Aaron Shaw', 'Luminary Games');
INSERT INTO Creators VALUES (42, 'Aaron Smith', 'A Smith Games');
INSERT INTO Creators VALUES (43, 'Aaron Sparke', 'Rule & Make');
INSERT INTO Creators VALUES (44, 'Aaron Toman', 'Iron Bear Studios');
INSERT INTO Creators VALUES (45, 'Aaron Vanderbeek', 'Banana Games');
INSERT INTO Creators VALUES (46, 'Aaron Watson', 'Playroom Entertainment');
INSERT INTO Creators VALUES (47, 'Aaron Weissblum', 'BLAM !');
INSERT INTO Creators VALUES (48, 'Aaron Yung', 'Black Locust Games');
INSERT INTO Creators VALUES (49, 'Aasmund Kaldestad', '(Self-Published)');
INSERT INTO Creators VALUES (50, 'Abe Nathanson', 'Bananagrams, Inc.');
INSERT INTO Creators VALUES (51, 'Abraham Edlin', 'Argo Games');
INSERT INTO Creators VALUES (52, 'Acchittocca', 'Hans im Glück');
INSERT INTO Creators VALUES (53, 'Ad Bruynzeel', 'Educa Borras');
INSERT INTO Creators VALUES (54, 'Adam A. Watts', 'Carpe Omnis Games');
INSERT INTO Creators VALUES (55, 'Adam Buckingham', 'Renegade Game Studios');
INSERT INTO Creators VALUES (56, 'Adam Carlson', 'Chip Theory Games');
INSERT INTO Creators VALUES (57, 'Adam Chunn', 'HutChu Enterprises LLC');
INSERT INTO Creators VALUES (58, 'Adam Collins', '25th Century Games');
INSERT INTO Creators VALUES (59, 'Adam Conus', 'Green Ronin Publishing');
INSERT INTO Creators VALUES (60, 'Adam E. Daulton', '2 Pionki');
INSERT INTO Creators VALUES (61, 'Adam F. Collins', 'Bearded Board Games');
INSERT INTO Creators VALUES (62, 'Adam Ferrel Trzonkowski', 'Epic Slant Press LLC');
INSERT INTO Creators VALUES (63, 'Adam Gertzbein', 'Pegasus Spiele');
INSERT INTO Creators VALUES (64, 'Adam Glass', 'Lost Age Games');
INSERT INTO Creators VALUES (65, 'Adam Godfroy', 'Mentalis Limited');
INSERT INTO Creators VALUES (66, 'Adam Hill', 'Devir');
INSERT INTO Creators VALUES (67, 'Adam Hogg', '(Self-Published)');
INSERT INTO Creators VALUES (68, 'Adam Kaluza', 'Rebel Sp. z o.o.');
INSERT INTO Creators VALUES (69, 'Adam Kwapinski', 'Awaken Realms');
INSERT INTO Creators VALUES (70, 'Adam L. Gruen', 'Fantasy Games Unlimited');
INSERT INTO Creators VALUES (71, 'Adam Loper', 'Snarling Badger Studios');
INSERT INTO Creators VALUES (72, 'Adam McCrimmon', 'XYZ Game Labs, Inc');
INSERT INTO Creators VALUES (73, 'Adam Mnich', 'Portal Games');
INSERT INTO Creators VALUES (74, 'Adam Niepomnik', 'Kenzer and Company');
INSERT INTO Creators VALUES (75, 'Adam P. McIver', 'Renegade Game Studios');