use board_games;


-- INSERT Mechanics (75 rows)
INSERT INTO Mechanics VALUES (1, 'Acting');
INSERT INTO Mechanics VALUES (2, 'Action Drafting');
INSERT INTO Mechanics VALUES (3, 'Action Points');
INSERT INTO Mechanics VALUES (4, 'Action Queue');
INSERT INTO Mechanics VALUES (5, 'Action Retrieval');
INSERT INTO Mechanics VALUES (6, 'Action Timer');
INSERT INTO Mechanics VALUES (7, 'Action/Event');
INSERT INTO Mechanics VALUES (8, 'Advantage Token');
INSERT INTO Mechanics VALUES (9, 'Alliances');
INSERT INTO Mechanics VALUES (10, 'Area Majority / Influence');
INSERT INTO Mechanics VALUES (11, 'Area Movement');
INSERT INTO Mechanics VALUES (12, 'Area-Impulse');
INSERT INTO Mechanics VALUES (13, 'Auction/Bidding');
INSERT INTO Mechanics VALUES (14, 'Auction: Dexterity');
INSERT INTO Mechanics VALUES (15, 'Auction: Dutch');
INSERT INTO Mechanics VALUES (16, 'Auction: Dutch Priority');
INSERT INTO Mechanics VALUES (17, 'Auction: English');
INSERT INTO Mechanics VALUES (18, 'Auction: Fixed Placement');
INSERT INTO Mechanics VALUES (19, 'Auction: Once Around');
INSERT INTO Mechanics VALUES (20, 'Auction: Sealed Bid');
INSERT INTO Mechanics VALUES (21, 'Auction: Turn Order Until Pass');
INSERT INTO Mechanics VALUES (22, 'Automatic Resource Growth');
INSERT INTO Mechanics VALUES (23, 'Betting and Bluffing');
INSERT INTO Mechanics VALUES (24, 'Bias');
INSERT INTO Mechanics VALUES (25, 'Bingo');
INSERT INTO Mechanics VALUES (26, 'Bribery');
INSERT INTO Mechanics VALUES (27, 'Campaign / Battle Card Driven');
INSERT INTO Mechanics VALUES (28, 'Card Drafting');
INSERT INTO Mechanics VALUES (29, 'Card Play Conflict Resolution');
INSERT INTO Mechanics VALUES (30, 'Catch the Leader');
INSERT INTO Mechanics VALUES (31, 'Chaining');
INSERT INTO Mechanics VALUES (32, 'Chit-Pull System');
INSERT INTO Mechanics VALUES (33, 'Closed Economy Auction');
INSERT INTO Mechanics VALUES (34, 'Command Cards');
INSERT INTO Mechanics VALUES (35, 'Commodity Speculation');
INSERT INTO Mechanics VALUES (36, 'Communication Limits');
INSERT INTO Mechanics VALUES (37, 'Connections');
INSERT INTO Mechanics VALUES (38, 'Constrained Bidding');
INSERT INTO Mechanics VALUES (39, 'Contracts');
INSERT INTO Mechanics VALUES (40, 'Cooperative Game');
INSERT INTO Mechanics VALUES (41, 'Crayon Rail System');
INSERT INTO Mechanics VALUES (42, 'Critical Hits and Failures');
INSERT INTO Mechanics VALUES (43, 'Cube Tower');
INSERT INTO Mechanics VALUES (44, 'Deck Construction');
INSERT INTO Mechanics VALUES (45, 'Deck, Bag, and Pool Building');
INSERT INTO Mechanics VALUES (46, 'Deduction');
INSERT INTO Mechanics VALUES (47, 'Delayed Purchase');
INSERT INTO Mechanics VALUES (48, 'Dice Rolling');
INSERT INTO Mechanics VALUES (49, 'Die Icon Resolution');
INSERT INTO Mechanics VALUES (50, 'Different Dice Movement');
INSERT INTO Mechanics VALUES (51, 'Drafting');
INSERT INTO Mechanics VALUES (52, 'Elapsed Real Time Ending');
INSERT INTO Mechanics VALUES (53, 'Enclosure');
INSERT INTO Mechanics VALUES (54, 'End Game Bonuses');
INSERT INTO Mechanics VALUES (55, 'Events');
INSERT INTO Mechanics VALUES (56, 'Finale Ending');
INSERT INTO Mechanics VALUES (57, 'Flicking');
INSERT INTO Mechanics VALUES (58, 'Follow');
INSERT INTO Mechanics VALUES (59, 'Force Commitment');
INSERT INTO Mechanics VALUES (60, 'Grid Coverage');
INSERT INTO Mechanics VALUES (61, 'Grid Movement');
INSERT INTO Mechanics VALUES (62, 'Hand Management');
INSERT INTO Mechanics VALUES (63, 'Hexagon Grid');
INSERT INTO Mechanics VALUES (64, 'Hidden Movement');
INSERT INTO Mechanics VALUES (65, 'Hidden Roles');
INSERT INTO Mechanics VALUES (66, 'Hidden Victory Points');
INSERT INTO Mechanics VALUES (67, 'Highest-Lowest Scoring');
INSERT INTO Mechanics VALUES (68, 'Hot Potato');
INSERT INTO Mechanics VALUES (69, 'I Cut, You Choose');
INSERT INTO Mechanics VALUES (70, 'Impulse Movement');
INSERT INTO Mechanics VALUES (71, 'Income');
INSERT INTO Mechanics VALUES (72, 'Increase Value of Unchosen Resources');
INSERT INTO Mechanics VALUES (73, 'Induction');
INSERT INTO Mechanics VALUES (74, 'Interrupts');
INSERT INTO Mechanics VALUES (75, 'Investment');